### ISSUE TITLE
Support sourcemaps

### ISSUE THREAD

**Issue by call-a3** [webpack-contrib/json-loader#14]
Title speaks for itself I think. There are two possible scenario's: 
- the loaded JSON was native JSON (without a sourcemap provided), which should result in a sourcemap that maps the JSON object in the outputted code to the original file
- the loaded JSON was the result of another pre-processing step (with an accompanying sourcemap), which should result in a new sourcemap that maintains the mappings of the previous sourcemaps, but combined with the wrapper code of this loader.

**Comment by SpaceK33z** [comment]
PR welcome.

**Comment by michael-ciniawsky** [comment]
Since `webpack >= v2.0.0` supports JSON natively now this should be fixed :)
