### ISSUE TITLE
Enable ES2015 syntax

### ISSUE THREAD

**Issue by call-a3** [webpack-contrib/json-loader#15]
Add a flag/option to use the new export syntax added in ES2015 instead of module.exports. 
Tools like babel used for post-processing might not be configured to recognize both module.exports/require and export/import.

This is a low priority issue, though should be (I think) easy to add.

**Comment by sokra** [comment]
I'll try to update all loaders when webpack 2 is stable...

**Comment by kevinSuttle** [comment]
Seems pretty stable now https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.25

**Comment by SpaceK33z** [comment]
#15 has the fix for this. It will be released around the webpack v2 stable release.

**Comment by michael-ciniawsky** [comment]
Since `webpack >= v2.0.0` has build-in support for JSON now, this is issue obsolete
