### ISSUE TITLE
Enable use of comments in json file (use json.minify)

### ISSUE THREAD

**Issue by emahuni** [webpack-contrib/json-loader#26]
I think it would be convinient to use [json.minify](https://github.com/getify/JSON.minify/tree/node) to enable and then remove the comments before parsing in json files.

I know comments are not allowed in json, but they are convinient for letting others/your future you, know whats going on without digging in source too much... especially in config files.

> Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser. - Douglas Crockford, 2012

**Comment by emahuni** [comment]
index.js

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
module.exports = function(source) {
	JSON.minify = require("node-json-minify");
	
	this.cacheable && this.cacheable();
	var value = typeof source === "string" ? JSON.parse(JSON.minify(source)) : source;
	this.value = [value];
	return "module.exports = " + JSON.stringify(value, undefined, "\t") + ";";
}

**Comment by emahuni** [comment]
package.json

```json
...

  "devDependencies": {
    "node-json-minify": "^1.0.0"
  },

...


```

**Comment by emahuni** [comment]
That works like a charm... I love this package, well-done man

**Comment by emahuni** [comment]
Added PR `Add json minify #29`

**Comment by michael-ciniawsky** [comment]
See #29, please use the [json5-loader](https://github.com/webpack-contrib/json5-loader) thx 😛
