### ISSUE TITLE
Use inputValues as shortcut?

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/json-loader#3]
I'm not sure if I understand [the docs](http://webpack.github.io/docs/loaders.html#inputvalues) correctly, but shouldn't the json-loader try to read from `inputValues` first?

I'm using @okonet's [yaml-loader](https://github.com/okonet/yaml-loader) which returns the parsed yaml as json string. After that the json-loader re-parses the string which is unnecessary.

**Comment by michael-ciniawsky** [comment]
@jhnns @okonet Is this still relevant somehow? 👀 Or can we close this 😛 ?

**Comment by okonet** [comment]
@michael-ciniawsky it doesn't look like I've updated the yaml-loader. Please feel free to submit a PR or I could transfer the loader to webpack-contrib org if this is more desirable.

**Comment by jhnns** [comment]
We deprecated the `inputValues` property, so this can be closed.

@okonet Regarding the yaml-loader: It would be nice if the yaml-loader would just generate an object and pass it on. The json-loader can handle inputs that are no strings.

I think, transferring the yaml-loader to webpack-contrib makes sense since yaml is a popular file format 👍

**Comment by michael-ciniawsky** [comment]
cc @bebraw @d3viant0ne

**Comment by bebraw** [comment]
I think @d3viant0ne can comment on the proper process. We've done it before with mixed results.
