### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by gilbertowa** [webpack-contrib/json-loader#30]
I would like to release a version to fix a loader error. Already I created a branch, but I can not do pull request (perhaps not have permission). Who can help me? The fix is ​​to avoid the error "Unexpected token m in JSON at position 0" that the loader generates the Angular 2 project

**Comment by oklas** [comment]
To make pull request you need to push your branch to repo.There is only one branch `master` in your repo. to put your repo do:

    git checkout your-branch
    git push origin your-branch:your-branch

and after that you can create pull request with your-branch to orininal repo where from your repo is forked.
