### ISSUE TITLE
Json encoding

### ISSUE THREAD

**Issue by dikond** [webpack-contrib/json-loader#50]
Hi folks,

I wanted to share one concern with you. 
Our `.json` file couldn't be processed due to some issue with Unicode encoding. Apparently, we had a [Line Separator char](http://www.fileformat.info/info/unicode/char/2028/index.htm) in the string literal. It was invisible in our text editors and we found with an empirical approach. I found [that answer on SO](http://stackoverflow.com/a/9168133/2533567) that explains why javascript fails to parse it.
I just think that it would be great to automatically escape this char in `json-loader` somehow. Or let a user know about the possible problem. What do you think?

**Comment by dwbruhn** [comment]
I'd like to echo the above comment and provide a minimal example demonstrating the problem:
https://github.com/dwbruhn/webpack-json-example

Looks like this issue has been open for a while...will someone be looking into it?

**Comment by dwbruhn** [comment]
Oh, looks like it was fixed but never published!
https://github.com/webpack-contrib/json-loader/commit/3b3069fa3f9deb35cc625c6c388e234a240ee312

Can someone publish it, please? @sokra

**Comment by d3viant0ne** [comment]
@dwbruhn - This plugins functionality is the default in Webpack > 2.

**Comment by dwbruhn** [comment]
Hi @d3viant0ne, but this is clearly a bug. Is there some blocker to publishing the fix?

**Comment by d3viant0ne** [comment]
My point is, if you are using webpack 2, you don't need this plugin.

If you are using webpack 1.x, it's not going to be supported for long & I will deprecate this the second it no longer is.

Fix, no fix, new version .... the right answer here is to use Webpack's native support for json and not a really soon to be moth-balled plugin.

**Comment by dwbruhn** [comment]
Hi @d3viant0ne, right, but it seems that webpack's "native support for json" [simply consists of including this module in its `package.json`](https://github.com/webpack/webpack/blob/4c6eb6f39f82096bfafe75f98f1007e28a88d366/package.json#L15).

And the github link on the [npm page for the module](https://www.npmjs.com/package/json-loader) redirects here.

You can see in [my example](https://github.com/dwbruhn/webpack-json-example) that I have no webpack plugins configured at all, and yet the problem appears.

Happy to be corrected, though, if I'm missing something!

**Comment by d3viant0ne** [comment]
iirc it's a lack of documentation issue in regards to Webpack's json support.

I'll get a version out as soon as I get back to my desk & see about getting the documentation issue resolved this weekend.

**Comment by d3viant0ne** [comment]
`json-loader@0.5.5` is available on npm. 

Change can be found here: https://github.com/webpack-contrib/json-loader/blob/master/CHANGELOG.md#055-2017-07-22

**Comment by dwbruhn** [comment]
Thanks! 👍
