### ISSUE TITLE
[v0.5.5] : JSON Object gets exported with default key (`harmony export`)

### ISSUE THREAD

**Issue by sasidhar** [webpack-contrib/json-loader#54]
Example :
**sample.json**
```
{
   "key1": "value1",
   "key2": "value2"
}
```
**Usage**
```
let data = require('./sample.json');
console.log(data);
```

With json-loader 0.5.4
```
{
    "key1": "value1",
    "key2": "value2"
}
```

With json-loader 0.5.5 : It is adding a wrapper object with key : 'default'.
```
{
    "default": {
        "key1": "value1",
        "key2": "value2"
    }
}
```

With this existing code is breaking.

FYI : Using https://github.com/AngularClass/angular-starter

**Comment by michael-ciniawsky** [comment]
@sasidhar Angular Starter uses `webpack >= v2.0.0`, which has native JSON support. This is a bug in Angular Starter aswell, so please open an issue there to remove `json-loader` from the seed :) The line causing this is [here](https://github.com/webpack-contrib/json-loader/blob/master/index.js#L10) and needs to be reverted to 

```js
var module = `module.exports = ${value}`
```

Ideally with a  ⚠️ warning in case `this.version >= 2`, I send PR asap :)
