### ISSUE TITLE
False positive warning about Webpack 2

### ISSUE THREAD

**Issue by gaearon** [webpack-contrib/json-loader#57]
We are seeing [this warning](https://github.com/webpack-contrib/json-loader/blob/525b28f9f4d44d9e7adf65fecf1e8d17c8c4a475/index.js#L12) on CI trying to update Create React App to Webpack 3: https://github.com/facebookincubator/create-react-app/pull/2574#issuecomment-317191139. However we never explicitly use `json-loader`.

I wonder if it's possible that the warning has a false positive? For example https://github.com/webpack/webpack/pull/3374 makes webpack delegate to `json-loader` automatically [here](https://github.com/webpack/webpack/blob/56b9aabc22067e5b5ccc303641ce420c60d7f389/lib/CompatibilityPlugin.js#L44-L52). Is there any chance that this could unintentionally trigger the warning?

**Comment by albertsaave** [comment]
+1

**Comment by scotmatson** [comment]
I noticed this issue when I have placed some dependencies for package.json under devDependencies. I have since moved everything back under dev and the warnings no longer occur.

**Comment by d3viant0ne** [comment]
@gaearon - I've stripped the deprecation warning entirely, this is a problem that needs to be fixed upstream as the whole thing is kind of circular.

`json-loader@0.5.7`

**Comment by gaearon** [comment]
Thanks!

**Comment by ollivierv** [comment]
Thank you @d3viant0ne ! With the "json-loader": "^0.5.7" in the package.json, we get rid of thoses "useless" warning messages ! 🥇
