### ISSUE TITLE
setup for require statements without file extension

### ISSUE THREAD

**Issue by hansondr** [webpack-contrib/json-loader#63]
I'm attempting to use a number of libraries which internally require JSON files but do so without specifying the `.json` file extension so I'm having difficulties in setting up my loader. e.g.

e.g.
`var listData = require('./list');` where **list** refers to a `list.json` in the package root.  If I manually edit the **index.js** to `var listData = require('./list.json');` then everything works as expected but editing the contents of a 3rd party library isn't a long-term solution.  My JSON loader is currently configured like so:

```
module.exports = {
  test: /\.json$/,
  loader: 'json-loader'
}
```

Is there an alternative configuration I should be using in order to utilize npm packages using JSON requires without an extension?

**Comment by michael-ciniawsky** [comment]
https://webpack.js.org/configuration/resolve/#resolve-extensions
